# Generated by Django 3.2.15 on 2022-09-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img',
            field=models.ImageField(default='sdfg', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
